package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"fmt"
	"log"
	"time"

	"github.com/neirth/openlobster/internal/application/graphql/generated"
	"github.com/neirth/openlobster/internal/application/graphql/resolvers/mappers"
	"github.com/neirth/openlobster/internal/domain/services/provideroauth"
)

// UpdateConfig is the resolver for the updateConfig field.
func (r *mutationResolver) UpdateConfig(ctx context.Context, input generated.UpdateConfigInput) (*generated.UpdateConfigResult, error) {
	if r.Deps == nil {
		return &generated.UpdateConfigResult{}, nil
	}
	m := mappers.UpdateConfigInputToMap(input)
	if err := r.Deps.UpdateConfig(ctx, m); err != nil {
		return nil, err
	}
	return mappers.AppConfigSnapshotToUpdateConfigResult(r.Deps.Config(ctx)), nil
}

// InitiateProviderOAuth is the resolver for the initiateProviderOAuth field.
func (r *mutationResolver) InitiateProviderOAuth(ctx context.Context, provider string, profileName *string) (*generated.InitiateProviderOAuthResult, error) {
	if r.Deps == nil || r.Deps.ProviderOAuthMgr == nil {
		return nil, fmt.Errorf("provider OAuth not configured")
	}

	type authInfo struct {
		url          string
		instructions string
	}
	authCh := make(chan authInfo, 1)
	errCh := make(chan error, 1)

	cb := provideroauth.LoginCallbacks{
		OnAuth: func(url string, instr string) {
			authCh <- authInfo{url: url, instructions: instr}
		},
		OnProgress: func(msg string) {
			log.Printf("provider-oauth: %s: %s", provider, msg)
		},
	}

	// Determine the profile name to use (default to "default" if not specified).
	profile := "default"
	if profileName != nil && *profileName != "" {
		profile = *profileName
	}

	// Start the login flow in a goroutine. It calls OnAuth with the URL
	// before blocking on the callback server, so we wait for that.
	go func() {
		if _, err := r.Deps.ProviderOAuthMgr.LoginWithProfile(context.Background(), provider, profile, cb); err != nil {
			log.Printf("provider-oauth: login failed for %s/%s: %v", provider, profile, err)
			errCh <- err
		} else {
			log.Printf("provider-oauth: login succeeded for %s/%s", provider, profile)
			// Auto-set oauth_provider and default model in config after successful login.
			if r.Deps.ConfigWriter != nil {
				defaultModel := provideroauth.GetDefaultModel(provider)
				configUpdate := map[string]interface{}{
					"oauthProvider": provider,
				}
				if defaultModel != "" {
					configUpdate["oauthModel"] = defaultModel
				}
				if _, applyErr := r.Deps.ConfigWriter.Apply(context.Background(), configUpdate); applyErr != nil {
					log.Printf("provider-oauth: failed to auto-set config for %s: %v", provider, applyErr)
				} else {
					log.Printf("provider-oauth: auto-set oauth_provider=%s oauth_model=%s", provider, defaultModel)
				}
			}
		}
	}()

	// Wait for the auth URL or an error (with timeout).
	select {
	case info := <-authCh:
		return &generated.InitiateProviderOAuthResult{
			AuthorizationURL: info.url,
			Instructions:     &info.instructions,
		}, nil
	case err := <-errCh:
		return nil, fmt.Errorf("provider %q login failed: %w", provider, err)
	case <-time.After(10 * time.Second):
		return nil, fmt.Errorf("provider %q login timed out waiting for auth URL", provider)
	}
}

// LogoutProviderOAuth is the resolver for the logoutProviderOAuth field.
func (r *mutationResolver) LogoutProviderOAuth(ctx context.Context, provider string) (bool, error) {
	if r.Deps == nil || r.Deps.ProviderOAuthMgr == nil {
		return false, fmt.Errorf("provider OAuth not configured")
	}
	if err := r.Deps.ProviderOAuthMgr.Logout(ctx, provider); err != nil {
		return false, err
	}
	return true, nil
}

// SetActiveOAuthProfile is the resolver for the setActiveOAuthProfile field.
func (r *mutationResolver) SetActiveOAuthProfile(ctx context.Context, provider string, profileName string) (bool, error) {
	if r.Deps == nil || r.Deps.ProviderOAuthMgr == nil {
		return false, fmt.Errorf("provider OAuth not configured")
	}
	if err := r.Deps.ProviderOAuthMgr.SetActiveProfile(ctx, provider, profileName); err != nil {
		return false, err
	}
	return true, nil
}

// DeleteOAuthProfile is the resolver for the deleteOAuthProfile field.
func (r *mutationResolver) DeleteOAuthProfile(ctx context.Context, provider string, profileName string) (bool, error) {
	if r.Deps == nil || r.Deps.ProviderOAuthMgr == nil {
		return false, fmt.Errorf("provider OAuth not configured")
	}
	if err := r.Deps.ProviderOAuthMgr.DeleteProfile(ctx, provider, profileName); err != nil {
		return false, err
	}
	return true, nil
}

// Config is the resolver for the config field.
func (r *queryResolver) Config(ctx context.Context) (*generated.AppConfig, error) {
	if r.Deps == nil {
		return &generated.AppConfig{}, nil
	}
	return mappers.AppConfigSnapshotToGenerated(r.Deps.Config(ctx)), nil
}

// ProviderOAuthProviders is the resolver for the providerOAuthProviders field.
func (r *queryResolver) ProviderOAuthProviders(ctx context.Context) ([]*generated.OAuthProviderInfo, error) {
	providers := provideroauth.List()
	out := make([]*generated.OAuthProviderInfo, len(providers))
	for i, p := range providers {
		out[i] = &generated.OAuthProviderInfo{
			ID:   p.ID(),
			Name: p.Name(),
		}
	}
	return out, nil
}

// ProviderOAuthStatus is the resolver for the providerOAuthStatus field.
func (r *queryResolver) ProviderOAuthStatus(ctx context.Context, provider string) (*generated.ProviderOAuthStatus, error) {
	if r.Deps == nil || r.Deps.ProviderOAuthMgr == nil {
		return &generated.ProviderOAuthStatus{
			Provider: provider,
			Status:   "not_configured",
		}, nil
	}

	if r.Deps.ProviderOAuthMgr.IsAuthenticated(ctx, provider) {
		return &generated.ProviderOAuthStatus{
			Provider: provider,
			Status:   "authenticated",
		}, nil
	}

	return &generated.ProviderOAuthStatus{
		Provider: provider,
		Status:   "not_authenticated",
	}, nil
}

// ProviderOAuthProfiles is the resolver for the providerOAuthProfiles field.
func (r *queryResolver) ProviderOAuthProfiles(ctx context.Context, provider string) ([]*generated.OAuthProfile, error) {
	if r.Deps == nil || r.Deps.ProviderOAuthMgr == nil {
		return nil, fmt.Errorf("provider OAuth not configured")
	}

	profiles, err := r.Deps.ProviderOAuthMgr.ListProfiles(ctx, provider)
	if err != nil {
		return nil, err
	}

	out := make([]*generated.OAuthProfile, len(profiles))
	for i, p := range profiles {
		out[i] = &generated.OAuthProfile{
			ID:            provider + "/" + p.Name,
			Name:          p.Name,
			ProviderID:    provider,
			Authenticated: p.Authenticated,
		}
		if p.AccountID != "" {
			out[i].AccountID = &p.AccountID
		}
	}
	return out, nil
}

// ProviderOAuthModels is the resolver for the providerOAuthModels field.
func (r *queryResolver) ProviderOAuthModels(ctx context.Context, provider string) ([]*generated.OAuthModel, error) {
	models := provideroauth.GetModels(provider)
	out := make([]*generated.OAuthModel, len(models))
	for i, m := range models {
		out[i] = &generated.OAuthModel{
			ID:        m.ID,
			Name:      m.Name,
			IsDefault: m.Default,
		}
	}
	return out, nil
}
